### ISSUE TITLE
Better exception logging

### ISSUE THREAD

**Issue by AW3i** [techdivision/import#162]
While importing products through a errorneous CSV file missing the SKU of a product, the pipeline step *product_import* threw an exception and the pipeline errored.
**the error**:
```
[2019-10-04 08:45:33] executor.INFO: 
In AbstractSubject.php line 1205:

  Found not supported data type "NULL" when preparing cache key in file /home/weigla/projects/magento2/project/src/var/pacemaker/pipelines/193/product-import_20191002-095901_01.csv on line 3901


In CacheKeyUtil.php line 88:

  Found not supported data type "NULL" when preparing cache key

import:products [--serial SERIAL] [--installation-dir INSTALLATION-DIR] [--system-name SYSTEM-NAME] [--pid-filename PID-FILENAME] [--cache-enabled CACHE-ENABLED] [--magento-edition MAGENTO-EDITION] [--magento-version MAGENTO-VERSION] [--configuration CONFIGURATION] [--source-dir SOURCE-DIR] [--target-dir TARGET-DIR] [--archive-dir ARCHIVE-DIR] [--archive-artefacts ARCHIVE-ARTEFACTS] [--source-date-format SOURCE-DATE-FORMAT] [--use-db-id USE-DB-ID] [--db-pdo-dsn DB-PDO-DSN] [--db-username DB-USERNAME] [--db-password DB-PASSWORD] [--log-level LOG-LEVEL] [--debug-mode DEBUG-MODE] [--single-transaction SINGLE-TRANSACTION] [--params PARAMS] [--params-file PARAMS-FILE] [--] [<operation-name>]

[EXCEPTION] /home/weigla/projects/magento2/project/src/vendor/techdivision/process-pipelines/Model/Executor/AbstractShellExecutor.php: Application run failed with error. See log for more information.%    

```
**the log file**
```
Exception: Found not supported data type "NULL" when preparing cache key in /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Utils/CacheKeyUtil.php:88
Stack trace:
#0 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Cache/LocalCacheAdapter.php(98): TechDivision\Import\Utils\CacheKeyUtil->cacheKey(NULL)
#1 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Cache/LocalCacheAdapter.php(110): TechDivision\Import\Cache\LocalCacheAdapter->cacheKey(NULL)
#2 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Cache/ConfigurableCacheAdapter.php(222): TechDivision\Import\Cache\LocalCacheAdapter->isCached(NULL)
#3 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-product/src/Repositories/ProductRepository.php(147): TechDivision\Import\Cache\ConfigurableCacheAdapter->isCached(NULL)
#4 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-product/src/Services/ProductBunchProcessor.php(942): TechDivision\Import\Product\Repositories\ProductRepository->findOneBySku(NULL)
#5 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-product/src/Observers/UrlKeyObserver.php(150): TechDivision\Import\Product\Services\ProductBunchProcessor->loadProduct(NULL)
#6 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-product/src/Observers/UrlKeyObserver.php(93): TechDivision\Import\Product\Observers\UrlKeyObserver->loadProduct(NULL)
#7 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-product/src/Observers/AbstractProductImportObserver.php(56): TechDivision\Import\Product\Observers\UrlKeyObserver->process()
#8 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Observers/GenericCompositeObserver.php(95): TechDivision\Import\Product\Observers\AbstractProductImportObserver->handle(Object(TechDivision\Import\Product\Ee\Subjects\EeBunchSubject))
#9 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Subjects/AbstractSubject.php(813): TechDivision\Import\Observers\GenericCompositeObserver->handle(Object(TechDivision\Import\Product\Ee\Subjects\EeBunchSubject))
#10 [internal function]: TechDivision\Import\Subjects\AbstractSubject->importRow(Array)
#11 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(149): call_user_func(Array, Array)
#12 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(135): TechDivision\Import\Adapter\Goodby\Interpreter->delegate(Array, Array)
#13 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Adapter/Goodby/Interpreter.php(74): TechDivision\Import\Adapter\Goodby\Interpreter->notify(Array)
#14 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Adapter/Goodby/Lexer.php(120): TechDivision\Import\Adapter\Goodby\Interpreter->interpret(Array)
#15 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Adapter/CsvImportAdapter.php(142): TechDivision\Import\Adapter\Goodby\Lexer->parse('/home/weigla/pr...', Object(TechDivision\Import\Adapter\Goodby\Interpreter))
#16 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Subjects/AbstractSubject.php(722): TechDivision\Import\Adapter\CsvImportAdapter->import(Array, '/home/weigla/pr...')
#17 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Plugins/SubjectExecutor.php(127): TechDivision\Import\Subjects\AbstractSubject->import('193', '/home/weigla/pr...')
#18 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(186): TechDivision\Import\Plugins\SubjectExecutor->execute(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject), Array, '193', '/home/weigla/pr...')
#19 /home/weigla/projects/magento2/project/src/vendor/techdivision/import/src/Plugins/SubjectPlugin.php(121): TechDivision\Import\Plugins\SubjectPlugin->processSubject(Object(TechDivision\Import\Configuration\Jms\Configuration\Subject))
#20 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-app-simple/src/Simple.php(647): TechDivision\Import\Plugins\SubjectPlugin->process()
#21 /home/weigla/projects/magento2/project/src/vendor/techdivision/import-cli/src/Command/AbstractImportCommand.php(108): TechDivision\Import\App\Simple->process('193')
#22 /home/weigla/projects/magento2/project/src/vendor/symfony/console/Command/Command.php(255): TechDivision\Import\Cli\Command\AbstractImportCommand->execute(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/weigla/projects/magento2/project/src/vendor/symfony/console/Application.php(893): Symfony\Component\Console\Command\Command->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/weigla/projects/magento2/project/src/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(TechDivision\Import\Cli\Command\ImportProductsCommand), Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/weigla/projects/magento2/project/src/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/weigla/projects/magento2/project/src/vendor/techdivision/pacemaker-import-m2if/bootstrap.php(56): Symfony\Component\Console\Application->run(Object(TechDivision\Import\Cli\Console\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/weigla/projects/magento2/project/src/vendor/techdivision/pacemaker-import-m2if/bin/import-m2if.php(54): require('/home/weigla/pr...')
#28 /home/weigla/projects/magento2/project/src/vendor/techdivision/pacemaker-import-m2if/bin/import-m2if(2): require('/home/weigla/pr...')
#29 {main}
```

The specified line in the log, doesn't match with the CSV line where the product is missing the SKU. 

I would suggest implementing a feature which would check the mandatory fields specified in a configuration file and if the field is empty in a row throw an exception, so that it's easier to debug faulty CSV import files.

**Comment by wagnert** [comment]
This feature has been released with version [3.8.0](https://github.com/techdivision/import-cli-simple/releases/tag/3.8.0).
